// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTW5dMwxBqFdOL7CT0793HRj0KSQsVC20',
    appId: '1:1055477226529:web:your-web-app-id',
    messagingSenderId: '1055477226529',
    projectId: 'poultrycare-70b88',
    authDomain: 'poultrycare-70b88.firebaseapp.com',
    storageBucket: 'poultrycare-70b88.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTW5dMwxBqFdOL7CT0793HRj0KSQsVC20',
    appId: '1:1055477226529:android:5f9b14675f564838ea9760',
    messagingSenderId: '1055477226529',
    projectId: 'poultrycare-70b88',
    storageBucket: 'poultrycare-70b88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMvY_vvki3EXyndXXHl81ECSgdVYquLag',
    appId: '1:1055477226529:ios:78173c768c92512eea9760',
    messagingSenderId: '1055477226529',
    projectId: 'poultrycare-70b88',
    storageBucket: 'poultrycare-70b88.firebasestorage.app',
    iosClientId: 'your-ios-client-id-here',
    iosBundleId: 'com.example.poultryFarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMvY_vvki3EXyndXXHl81ECSgdVYquLag',
    appId: '1:1055477226529:ios:78173c768c92512eea9760',
    messagingSenderId: '1055477226529',
    projectId: 'poultrycare-70b88',
    storageBucket: 'poultrycare-70b88.firebasestorage.app',
    iosClientId: 'your-ios-client-id-here',
    iosBundleId: 'com.example.poultryFarm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTW5dMwxBqFdOL7CT0793HRj0KSQsVC20',
    appId: '1:1055477226529:android:5f9b14675f564838ea9760',
    messagingSenderId: '1055477226529',
    projectId: 'poultrycare-70b88',
    storageBucket: 'poultrycare-70b88.firebasestorage.app',
  );
}
